config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :courses
  resources :classrooms

  root 'classrooms#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :course
	belongs_to :student

	validates_presence_of :course_id, :student_id
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :classrooms
	has_many :students, :through => :classrooms

	has_enumeration_for :status, :with => CourseStatus

	validates_presence_of :name, :description, :status
	validates_length_of :name, maximum: 45, allow_blank: false
	validates_length_of :description, maximum: 45, allow_blank: false

end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :classrooms
	has_many :courses,  :through => :classrooms

	has_enumeration_for :status, :with => StudentStatus

	validates_presence_of :name, :register_number, :status
	validates_length_of :name, maximum: 45, allow_blank: false
	validates_length_of :register_number, maximum: 45, allow_blank: false

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController

	def index
		@classrooms = Classroom.take(5)
	end

	def new
		@classroom = Classroom.new
	end

	def create
		@classroom = Classroom.new(classroom_params)

		if @classroom.save
			redirect_to action: "index", notice: "Created with successful"
		else
			render action: :new
		end
	end

	def destroy
		@classroom = Classroom.find(params[:id])

		if @classroom.delete
			redirect_to action: "index", notice: "Deleted with successful"
		else
			redirect_to action: "index", notice: "Deleted was failed"
		end

	end

	private

	def classroom_params
		params.require(:classroom).permit(:course_id, :student_id)
	end


end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	def index
		@courses = Course.all
	end

	def new
		@course = Course.new
	end

	def create
		@course = Course.new(course_params)

		if @course.save
			redirect_to @course, notice: "Created with successful"
		else
			render action: :new
		end
	end

	def show
		@course = Course.find(params[:id])
	end

	def edit
		@course = Course.find(params[:id])
	end

	def update
		@course = Course.find(params[:id])

		if @course.update(course_params)
			redirect_to @course, notice: "Updated with successful"
		else
			render action: :edit
		end
	end

	private 

	def course_params
		params.require(:course).permit(:name, :description, :status)
	end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def index
		@students = Student.all
	end

	def new
		@student = Student.new
	end

	def create
		@student = Student.new(student_params)

		if @student.save
			redirect_to @student, notice: "Created with successful"
		else
			render action: :new
		end
	end

	def show
		@student = Student.find(params[:id])
	end

	def edit
		@student = Student.find(params[:id])
	end

	def update
		@student = Student.find(params[:id])

		if @student.update(student_params)
			redirect_to @student, notice: "Updated with successful"
		else
			render action: :edit
		end
	end

	private 

	def student_params
		params.require(:student).permit(:name, :register_number, :status)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/classrooms/_form.html.erb
<% if @classroom.errors.any? %>
	<p class="bg-danger">
		There are some errors in the form, please check it.
	</p>
<% end %>

<%= simple_form_for @classroom do |f| %>

	<div class="form-group">
		<%= f.association :student, input_html: { class: 'form-control' } %>
	</div>

	<div class="form-group">
		<%= f.association :course, input_html: { class: 'form-control' } %>
	</div>


	<button class="btn btn-default" type="submit">Register</button>

<% end %>

app/views/classrooms/edit.html.erb
<h1> Edit Registration </h1>

<%= render 'form' %>

app/views/classrooms/index.html.erb
<h1> <%= t 'register.registrations' %> </h1>

<p class="text-info"><%= notice %></p>

<table class="table table-bordered">
	<thead>
		<tr>
			<th><%= t 'activerecord.attributes.classroom.student' %></th>
			<th><%= t 'activerecord.attributes.classroom.course' %> </th>
			<th><%= t 'activerecord.attributes.classroom.created_at' %></th>
			<th></th>
		</tr>	
	</thead>

	<tbody>
		
		<% @classrooms.each do |classroom| %>
			<tr>
				<td><%= classroom.student.name %></td>
				<td><%= classroom.course.name %></td>
				<td><%= classroom.created_at %></td>
				<td><%= link_to t("links.delete"), classroom_path(classroom), method: :delete, data: { confirm: t('messages.remove_classroom') } %></td>
			</tr>
		<% end %>

	</tbody>

</table>

<%= link_to t('register.new'), new_classroom_path , {role: 'button', class:'btn btn-default'} %>

app/views/classrooms/new.html.erb
<h1> New Registration </h1>

<%= render 'form' %>
	

app/views/courses/_form.html.erb
<% if @course.errors.any? %>
	<p class="bg-danger">
		There are some errors in the form, please check it.
	</p>
<% end %>

<%= simple_form_for @course do |f| %>

	<div class="form-group">
		<%= f.input :name, input_html: { class: 'form-control' } %>
	</div>

	<div class="form-group">
		<%= f.input :description, input_html: { class: 'form-control' } %>
	</div>

	<div class="form-group">
		<%= f.input :status, collection: CourseStatus.to_a , input_html: { class: 'form-control' } %>
	</div>


	<%= f.submit :class => "btn btn-default" %>

<% end %>

app/views/courses/edit.html.erb
<h1> Edit Course </h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<h1> <%= t 'links.courses' %> </h1>

<table class="table table-bordered">
	<thead>
		<tr>
			<th> <%= t 'activerecord.attributes.course.name' %> </th>
			<th> <%= t 'activerecord.attributes.course.description' %> </th>
			<th> Status </th>
		</tr>	
	</thead>

	<tbody>
		
		<% @courses.each do |course| %>
			<tr>
				<td><%= course.name %></td>
				<td><%= course.description %></td>
				<td><%= course.status_humanize %></td>
			</tr>
		<% end %>

	</tbody>

</table>

<%= link_to t('links.course.new'),  new_course_path, {role: 'button', class:'btn btn-default'} %>

app/views/courses/new.html.erb
<h1><%= t 'links.course.new' %></h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<p class="text-info"><%= notice %></p>

<h4> View Course </h4>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= CourseStatus.key_for(@course.status) %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  	<title>ProficiencyTest</title>
  	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  	<!-- Bootstrap Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>

</head>
<body>

	<header>
			<h1><%= link_to "school.net", root_path %></h1>
			<nav>
				<ul>
					<li><%= link_to t('links.courses'), courses_path %></li>
					<li><%= link_to t('links.students'), students_path %></li>
				</ul>
			</nav>
		</div>
	</header>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/students/_form.html.erb
<% if @student.errors.any? %>
	<p class="bg-danger">
		There are some errors in the form, please check it.
	</p>
<% end %>

<%= simple_form_for @student do |f| %>

	<div class="form-group">
		<%= f.input :name, input_html: { class: 'form-control' } %>
	</div>

	<div class="form-group">
		<%= f.input :register_number, input_html: { class: 'form-control' } %>
	</div>

	<div class="form-group">
		<%= f.input :status, collection: StudentStatus.to_a , input_html: { class: 'form-control' } %>
	</div>


	<%= f.submit :class => "btn btn-default" %>

<% end %>

app/views/students/edit.html.erb
<h1> Edit Student </h1>

<%= render 'form' %>

app/views/students/index.html.erb
<h1> <%= t 'links.students' %> </h1>

<table class="table table-bordered">
	<thead>
		<tr>
			<th> <%= t 'activerecord.attributes.student.name' %> </th>
			<th> <%= t 'activerecord.attributes.student.register_number' %> </th>
			<th> Status </th>
			<th></th>
		</tr>	
	</thead>

	<tbody>
		
		<% @students.each do |student| %>
			<tr>
				<td><%= student.name %></td>
				<td><%= student.register_number %></td>
				<td><%= student.status_humanize %></td>
				<td><%= link_to t('links.edit'),  edit_student_path(student) %></td>
			</tr>
		<% end %>

	</tbody>

</table>

<%= link_to 'New Student',  new_student_path, {role: 'button', class:'btn btn-default'}  %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

app/views/students/show.html.erb
<p class="text-info"><%= notice %></p>

<h4> View Student </h4>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Register Number:</strong>
  <%= @student.register_number %>
</p>

<p>
  <strong>Status:</strong>
  <%= @student.status_humanize %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>